const std = @import("std");

// Error codes matching librdkafka v2.13.0
pub const rd_kafka_resp_err_t = enum(c_int) {
    // Internal errors (librdkafka-specific, -200 to -100)
    _BEGIN = -200,
    _BAD_MSG = -199,
    _BAD_COMPRESSION = -198,
    _DESTROY = -197,
    _FAIL = -196,
    _TRANSPORT = -195,
    _CRIT_SYS_RESOURCE = -194,
    _RESOLVE = -193,
    _MSG_TIMED_OUT = -192,
    _PARTITION_EOF = -191,
    _UNKNOWN_PARTITION = -190,
    _FS = -189,
    _UNKNOWN_TOPIC = -188,
    _ALL_BROKERS_DOWN = -187,
    _INVALID_ARG = -186,
    _TIMED_OUT = -185,
    _QUEUE_FULL = -184,
    _ISR_INSUFF = -183,
    _NODE_UPDATE = -182,
    _SSL = -181,
    _WAIT_COORD = -180,
    _UNKNOWN_GROUP = -179,
    _IN_PROGRESS = -178,
    _PREV_IN_PROGRESS = -177,
    _EXISTING_SUBSCRIPTION = -176,
    _ASSIGN_PARTITIONS = -175,
    _REVOKE_PARTITIONS = -174,
    _CONFLICT = -173,
    _STATE = -172,
    _UNKNOWN_PROTOCOL = -171,
    _NOT_IMPLEMENTED = -170,
    _AUTHENTICATION = -169,
    _NO_OFFSET = -168,
    _OUTDATED = -167,
    _TIMED_OUT_QUEUE = -166,
    _UNSUPPORTED_FEATURE = -165,
    _WAIT_CACHE = -164,
    _INTR = -163,
    _KEY_SERIALIZATION = -162,
    _VALUE_SERIALIZATION = -161,
    _KEY_DESERIALIZATION = -160,
    _VALUE_DESERIALIZATION = -159,
    _PARTIAL = -158,
    _READ_ONLY = -157,
    _NOENT = -156,
    _UNDERFLOW = -155,
    _INVALID_TYPE = -154,
    _RETRY = -153,
    _PURGE_QUEUE = -152,
    _PURGE_INFLIGHT = -151,
    _FATAL = -150,
    _INCONSISTENT = -149,
    _GAPLESS_GUARANTEE = -148,
    _MAX_POLL_EXCEEDED = -147,
    _UNKNOWN_BROKER = -146,
    _NOT_CONFIGURED = -145,
    _FENCED = -144,
    _APPLICATION = -143,
    _ASSIGNMENT_LOST = -142,
    _NOOP = -141,
    _AUTO_OFFSET_RESET = -140,
    _LOG_TRUNCATION = -139,
    _END = -100,

    // Kafka broker errors (0-100+)
    NO_ERROR = 0,
    OFFSET_OUT_OF_RANGE = 1,
    CORRUPT_MESSAGE = 2,
    UNKNOWN_TOPIC_OR_PARTITION = 3,
    INVALID_FETCH_SIZE = 4,
    LEADER_NOT_AVAILABLE = 5,
    NOT_LEADER_FOR_PARTITION = 6,
    REQUEST_TIMED_OUT = 7,
    BROKER_NOT_AVAILABLE = 8,
    REPLICA_NOT_AVAILABLE = 9,
    MESSAGE_TOO_LARGE = 10,
    STALE_CONTROLLER_EPOCH = 11,
    OFFSET_METADATA_TOO_LARGE = 12,
    NETWORK_EXCEPTION = 13,
    COORDINATOR_LOAD_IN_PROGRESS = 14,
    COORDINATOR_NOT_AVAILABLE = 15,
    NOT_COORDINATOR = 16,
    INVALID_TOPIC_EXCEPTION = 17,
    RECORD_LIST_TOO_LARGE = 18,
    NOT_ENOUGH_REPLICAS = 19,
    NOT_ENOUGH_REPLICAS_AFTER_APPEND = 20,
    INVALID_REQUIRED_ACKS = 21,
    ILLEGAL_GENERATION = 22,
    INCONSISTENT_GROUP_PROTOCOL = 23,
    INVALID_GROUP_ID = 24,
    UNKNOWN_MEMBER_ID = 25,
    INVALID_SESSION_TIMEOUT = 26,
    REBALANCE_IN_PROGRESS = 27,
    INVALID_COMMIT_OFFSET_SIZE = 28,
    TOPIC_AUTHORIZATION_FAILED = 29,
    GROUP_AUTHORIZATION_FAILED = 30,
    CLUSTER_AUTHORIZATION_FAILED = 31,
    INVALID_TIMESTAMP = 32,
    UNSUPPORTED_SASL_MECHANISM = 33,
    ILLEGAL_SASL_STATE = 34,
    UNSUPPORTED_VERSION = 35,
    TOPIC_ALREADY_EXISTS = 36,
    INVALID_PARTITIONS = 37,
    INVALID_REPLICATION_FACTOR = 38,
    INVALID_REPLICA_ASSIGNMENT = 39,
    INVALID_CONFIG = 40,
    NOT_CONTROLLER = 41,
    INVALID_REQUEST = 42,
    UNSUPPORTED_FOR_MESSAGE_FORMAT = 43,
    POLICY_VIOLATION = 44,
    OUT_OF_ORDER_SEQUENCE_NUMBER = 45,
    DUPLICATE_SEQUENCE_NUMBER = 46,
    INVALID_PRODUCER_EPOCH = 47,
    INVALID_TXN_STATE = 48,
    INVALID_PRODUCER_ID_MAPPING = 49,
    INVALID_TRANSACTION_TIMEOUT = 50,
    CONCURRENT_TRANSACTIONS = 51,
    TRANSACTION_COORDINATOR_FENCED = 52,
    TRANSACTIONAL_ID_AUTHORIZATION_FAILED = 53,
    SECURITY_DISABLED = 54,
    OPERATION_NOT_ATTEMPTED = 55,
    KAFKA_STORAGE_ERROR = 56,
    LOG_DIR_NOT_FOUND = 57,
    SASL_AUTHENTICATION_FAILED = 58,
    UNKNOWN_PRODUCER_ID = 59,
    REASSIGNMENT_IN_PROGRESS = 60,
    DELEGATION_TOKEN_AUTH_DISABLED = 61,
    DELEGATION_TOKEN_NOT_FOUND = 62,
    DELEGATION_TOKEN_OWNER_MISMATCH = 63,
    DELEGATION_TOKEN_REQUEST_NOT_ALLOWED = 64,
    DELEGATION_TOKEN_AUTHORIZATION_FAILED = 65,
    DELEGATION_TOKEN_EXPIRED = 66,
    INVALID_PRINCIPAL_TYPE = 67,
    NON_EMPTY_GROUP = 68,
    GROUP_ID_NOT_FOUND = 69,
    FETCH_SESSION_ID_NOT_FOUND = 70,
    INVALID_FETCH_SESSION_EPOCH = 71,
    LISTENER_NOT_FOUND = 72,
    TOPIC_DELETION_DISABLED = 73,
    FENCED_LEADER_EPOCH = 74,
    UNKNOWN_LEADER_EPOCH = 75,
    UNSUPPORTED_COMPRESSION_TYPE = 76,
    STALE_BROKER_EPOCH = 77,
    OFFSET_NOT_AVAILABLE = 78,
    MEMBER_ID_REQUIRED = 79,
    PREFERRED_LEADER_NOT_AVAILABLE = 80,
    GROUP_MAX_SIZE_REACHED = 81,
    FENCED_INSTANCE_ID = 82,
    ELIGIBLE_LEADERS_NOT_AVAILABLE = 83,
    ELECTION_NOT_NEEDED = 84,
    NO_REASSIGNMENT_IN_PROGRESS = 85,
    GROUP_SUBSCRIBED_TO_TOPIC = 86,
    INVALID_RECORD = 87,
    UNSTABLE_OFFSET_COMMIT = 88,
    THROTTLING_QUOTA_EXCEEDED = 89,
    PRODUCER_FENCED = 90,
    RESOURCE_NOT_FOUND = 91,
    DUPLICATE_RESOURCE = 92,
    UNACCEPTABLE_CREDENTIAL = 93,
    INCONSISTENT_VOTER_SET = 94,
    INVALID_UPDATE_VERSION = 95,
    FEATURE_UPDATE_FAILED = 96,
    PRINCIPAL_DESERIALIZATION_FAILURE = 97,
    _,
};

// Error string table
const error_strings = std.StaticStringMap([]const u8).initComptime(.{
    .{ "_MSG_TIMED_OUT", "Local: Message timed out" },
    .{ "_QUEUE_FULL", "Local: Queue full" },
    .{ "_UNKNOWN_TOPIC", "Local: Unknown topic" },
    .{ "_ALL_BROKERS_DOWN", "Local: All broker connections down" },
    .{ "_INVALID_ARG", "Local: Invalid argument" },
    .{ "_TIMED_OUT", "Local: Operation timed out" },
    .{ "_UNKNOWN_PARTITION", "Local: Unknown partition" },
    .{ "_FS", "Local: File or filesystem error" },
    .{ "_UNKNOWN_GROUP", "Local: Unknown group" },
    .{ "_NOT_IMPLEMENTED", "Local: Not implemented" },
    .{ "_AUTHENTICATION", "Local: Authentication failure" },
    .{ "_NO_OFFSET", "Local: No offset stored" },
    .{ "NO_ERROR", "Success" },
    .{ "OFFSET_OUT_OF_RANGE", "Broker: Offset out of range" },
    .{ "CORRUPT_MESSAGE", "Broker: Corrupt message" },
    .{ "UNKNOWN_TOPIC_OR_PARTITION", "Broker: Unknown topic or partition" },
    .{ "INVALID_FETCH_SIZE", "Broker: Invalid fetch size" },
    .{ "LEADER_NOT_AVAILABLE", "Broker: Leader not available" },
    .{ "NOT_LEADER_FOR_PARTITION", "Broker: Not leader for partition" },
    .{ "REQUEST_TIMED_OUT", "Broker: Request timed out" },
    .{ "BROKER_NOT_AVAILABLE", "Broker: Broker not available" },
    .{ "REPLICA_NOT_AVAILABLE", "Broker: Replica not available" },
    .{ "MESSAGE_TOO_LARGE", "Broker: Message too large" },
    .{ "STALE_CONTROLLER_EPOCH", "Broker: Stale controller epoch" },
    .{ "OFFSET_METADATA_TOO_LARGE", "Broker: Offset metadata too large" },
    .{ "NETWORK_EXCEPTION", "Broker: Network exception" },
    .{ "COORDINATOR_LOAD_IN_PROGRESS", "Broker: Coordinator load in progress" },
    .{ "COORDINATOR_NOT_AVAILABLE", "Broker: Coordinator not available" },
    .{ "NOT_COORDINATOR", "Broker: Not coordinator" },
    .{ "INVALID_TOPIC_EXCEPTION", "Broker: Invalid topic" },
    .{ "RECORD_LIST_TOO_LARGE", "Broker: Record list too large" },
    .{ "NOT_ENOUGH_REPLICAS", "Broker: Not enough replicas" },
    .{ "NOT_ENOUGH_REPLICAS_AFTER_APPEND", "Broker: Not enough replicas after append" },
    .{ "INVALID_REQUIRED_ACKS", "Broker: Invalid required acks" },
    .{ "ILLEGAL_GENERATION", "Broker: Illegal generation" },
    .{ "INCONSISTENT_GROUP_PROTOCOL", "Broker: Inconsistent group protocol" },
    .{ "INVALID_GROUP_ID", "Broker: Invalid group id" },
    .{ "UNKNOWN_MEMBER_ID", "Broker: Unknown member id" },
    .{ "INVALID_SESSION_TIMEOUT", "Broker: Invalid session timeout" },
    .{ "REBALANCE_IN_PROGRESS", "Broker: Rebalance in progress" },
    .{ "INVALID_COMMIT_OFFSET_SIZE", "Broker: Invalid commit offset size" },
    .{ "TOPIC_AUTHORIZATION_FAILED", "Broker: Topic authorization failed" },
    .{ "GROUP_AUTHORIZATION_FAILED", "Broker: Group authorization failed" },
    .{ "CLUSTER_AUTHORIZATION_FAILED", "Broker: Cluster authorization failed" },
    .{ "INVALID_TIMESTAMP", "Broker: Invalid timestamp" },
    .{ "UNSUPPORTED_SASL_MECHANISM", "Broker: Unsupported SASL mechanism" },
    .{ "ILLEGAL_SASL_STATE", "Broker: Illegal SASL state" },
    .{ "UNSUPPORTED_VERSION", "Broker: Unsupported version" },
    .{ "TOPIC_ALREADY_EXISTS", "Broker: Topic already exists" },
    .{ "INVALID_PARTITIONS", "Broker: Invalid partitions" },
    .{ "INVALID_REPLICATION_FACTOR", "Broker: Invalid replication factor" },
});

export fn rd_kafka_err2str(err: rd_kafka_resp_err_t) callconv(.C) [*:0]const u8 {
    const name = @tagName(err);
    if (error_strings.get(name)) |str| {
        return str.ptr;
    }
    return "Unknown error";
}

export fn rd_kafka_err2name(err: rd_kafka_resp_err_t) callconv(.C) [*:0]const u8 {
    return @tagName(err).ptr;
}

export fn rd_kafka_last_error() callconv(.C) rd_kafka_resp_err_t {
    // Return thread-local error if we implement that later
    return .NO_ERROR;
}
